version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.8-fpm-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup SDKs
          command: php build_sdk.php
